### ISSUE TITLE
Different between react-dragula and dragula?

### ISSUE THREAD

**Issue by hieuhlc** [bevacqua/react-dragula#16]
I want to know properly what different between react-dragula and normal dragula. If I use normal dragula in a React project, not use react version of it, then what is the side effect?

Just curious, because I used normal version and still found nothing wrong.
Thank you.

**Comment by sgtpepper43** [comment]
All it _did_ do was remove the `data-reactid` attributes on nodes when you move them, so that React doesn't throw exceptions. However, React 15 removed the `data-reactid` attribute (besides when you server side render it, but even then its not everywhere), so if you're on React 15, this library does literally nothing.

**Comment by m-andrew-albright** [comment]
This library _should_ provide a way to intercept the drop action, and allow you to modify your own state based on indexes (or something).  Instead, it allows you to move DOM nodes around, but I can't imagine many scenarios where that is actually useful on its own.
